stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "root/cloud_project_terraform/"
  TF_VAR_endpoint: "http://20.20.20.11:2633/RPC2"
  TF_VAR_username: "oneadmin"
  TF_VAR_password: "BehWLSlDa3"
  REMOTE_HOST: "root@20.20.20.30"

before_script:
  - apk add --no-cache openssh
  - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

validate:
  stage: validate
  script:
    - ssh $REMOTE_HOST "cd $TF_ROOT && terraform init && terraform validate"

plan:
  stage: plan
  script:
    - ssh $REMOTE_HOST "cd $TF_ROOT && terraform plan -out=tfplan"

apply:
  stage: apply
  script:
    - ssh $REMOTE_HOST "cd $TF_ROOT && terraform apply -auto-approve tfplan"
  when: manual
